service: happiness-index

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

plugins:
  - serverless-offline

functions:
  register:
    handler: registration.oauth
    events:
      - http:
          path: auth
          method: get
          cors: true
